{
	{ "Cheer", "shirt", "red white cheerleader top", 5 },
	{ "Nephew", "shirt", "white shirt black tie", 20 }, { "Nephew", "face", "black sunglasses", 500 }, { "Nephew", "hair", "slicked back blonde hair", 200 },
	{ "Moustache", "shirt", "brown sweater vest bow tie", 5 }, { "Moustache", "face", "monocle", 100 }, { "Moustache", "hair", "neat brown hair side part", 200 },
	{ "Genius", "shirt", "purple shirt", 10 },
	{ "Ghost", "hat", "ghost sheet costume", 50 }, { "Ghost", "shirt", "white ghost", 5 },
	{ "Time", "hat", "steampunk goggles", 100 }, { "Time", "shirt", "orange futuristic jacket", 5 }, { "Time", "hair", "messy ginger hair", 200 },
	{ "NewKid", "shirt", "black hoodie", 50 }, { "NewKid", "hat", "black hood", 200 },
	{ "Rocket", "shirt", "astronaut suit", 20 }, { "Rocket", "pants", "astronaut pants", 10 }, { "Rocket", "hat", "astronaut helmet", 200 },
	{ "Prof", "shirt", "tweed jacket bow tie", 5 }, { "Prof", "hair", "white fluffy hair", 100 }, { "Prof", "face", "round glasses gold", 100 },
	{ "Pop", "shirt", "sparkly pink jacket", 10 }, { "Pop", "hair", "pink hair", 300 }, { "Pop", "face", "star sunglasses", 100 },
	{ "Grand", "shirt", "white shirt black vest", 20 },
	{ "CEO", "shirt", "black suit red tie", 20 }, { "CEO", "pants", "black suit pants", 50 }, { "CEO", "hair", "slicked back black hair", 200 },
	{ "Wifi", "shirt", "cyan hoodie", 10 }, { "Wifi", "hair", "blue messy hair", 200 },
	{ "Sub", "shirt", "brown trench coat", 20 }, { "Sub", "pants", "brown trench coat", 10 }, { "Sub", "hat", "brown fedora", 200 }, { "Sub", "face", "fake glasses moustache", 50 },
	{ "Snow", "shirt", "light blue winter coat", 10 }, { "Snow", "hat", "snowflake beanie", 50 },
	{ "Reminder", "shirt", "dark red blazer", 10 }, { "Reminder", "back", "black cape", 200 }, { "Reminder", "hair", "black spiky hair villain", 200 },
	{ "Glitch", "shirt", "glitch", 50 }, { "Glitch", "pants", "glitch pants", 20 },
	{ "Grandpa", "hair", "white hair old man", 50 }, { "Grandpa", "face", "white beard", 100 }, { "Grandpa", "shirt", "maroon graduation gown", 5 },
	{ "Class99", "shirt", "blue windbreaker", 10 }, { "Class99", "hair", "frosted tips", 50 },
	{ "Prefect", "shirt", "black school blazer badge", 10 }, { "Prefect", "hair", "neat blonde hair", 200 },
	{ "Founder", "hat", "black top hat", 300 }, { "Founder", "face", "grey beard", 100 }, { "Founder", "shirt", "brown frock coat victorian", 5 },
	{ "TinyP", "shirt", "grey suit tie", 20 }, { "TinyP", "pants", "grey suit pants", 20 }, { "TinyP", "face", "mustache", 200 },
}
